---
version: '3'
services:
  web:
    build: .
    ports:
      - "80:8080"
    environment:
      - DB_HOSTNAME=mongo
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /opt/relink/data:/data/db
